### PR TITLE
Oauth n stripe bugs

### PR DESCRIPTION
**Pull request by KryoKorpz**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change status
- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by KryoKorpz** [comment]
the django-oauth-toolkit was never added to the project; ya'll were able to bypass that by running a migrate that added the table directly; but this prevented heroku from deploying since that package was not available during build and unable to migrate afterwards

I forced a deploy and got it to build without it; but still wasn't able to migrate server side for a properly functioning build

**Comment by AlexisReyes90** [comment]
What? I saw lisa install it... I don't know then...

**Comment by KryoKorpz** [comment]
Git was being an absolute nightmare yesterday;

**Comment by AlexisReyes90** [comment]
Man, that's a mess.

**Comment by ravb2019** [comment]
Just wondering why customerID was changed to customer_ID. Are we following any naming convention ?

**Comment by KryoKorpz** [comment]
No naming convention it was what your changes required; whatever you altered for stripe integration requires that field; you named it one thing but you or stripes integration required it to be named what I changed it to

**Pull request merged**
