### PR TITLE
Email rework

### PR DESCRIPTION
**Pull request by KryoKorpz**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change status
- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by KryoKorpz** [comment]
Most of the issues have been resolved; I will complete the sendgrid part and then it can be merged as I will need help with styling and hopefully Bhavik can help easily implement those drop downs

**Comment by KryoKorpz** [comment]
Unfortunately sendgrid doesn't support more than a 72 hr delay of sending email. I apologize for overlooking this. I have left the code in to support sending at set time frames 2d, 2w, 2m from the send email button being selected.
PR ready to be merged

**Comment by KryoKorpz** [comment]
Don't have time to get this merged before I need to continue building on it. Was hoping it would have gotten approved and merged yesterday. 

I will be working on it I'll let ya know when it's ready to merge

**Comment by holly-g** [comment]
@KryoKorpz Could you also edit the placeholder text in SendEmail while you're working on this? :) 
screenshot 2019-02-14 at 12 34 45 pm
screenshot 2019-02-14 at 12 34 51 pm

**Comment by KryoKorpz** [comment]
Spent the past 4.5 hours trying to get the delayed send functional. Windows is incompatible with most of the scheduling frameworks. And I was unable to get the python one functioning. But unfortunately we will not have that functionality for the code review.
PR as complete as it's going to be, ready for merge

**Pull request merged**
