### PR TITLE
Settings landing page

### PR DESCRIPTION
**Pull request by LisaCee**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ X] New feature (non-breaking change which adds functionality)

## Change status
- [ ] Complete, tested, ready to review and merge
- [X] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Ran local host 3000 and viewed changes locally

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Comment by LisaCee** [comment]
@ravb2019 Fixed it!

**Comment by LisaCee** [comment]
@KryoKorpz Good catch!  Updated.

**Comment by LisaCee** [comment]
@KryoKorpz and done!

I think we may need to look at our registration page and teacher model a bit more.  We never ask for email when registering a new teacher and we don't have a password field in the model.

**Comment by KryoKorpz** [comment]
Good call; updated Trello

**Comment by KryoKorpz** [comment]
Need to work on my review skills....
line 22 we can remove the console.log

**Comment by LisaCee** [comment]
I need to work on my github checking skills too.

**Pull request merged**
