### PR TITLE
Delete Rocket

### PR DESCRIPTION
**Pull request by KryoKorpz**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change status
- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by KryoKorpz** [comment]
#143

**Comment by AlexisReyes90** [comment]
Is this tested? I wonder if we need to adjust the actions/ reducer, but I don't think we need to bother with the reducer. Reloading the state (when the delete rocket happens) should refresh with the one removed anyways.

**Comment by KryoKorpz** [comment]
I tested it; and I did add a new action; current actions shouldn't be affected though

**Comment by AlexisReyes90** [comment]
Alright. Should be good as long as the state refreshes then.

**Comment by KryoKorpz** [comment]
react auto refreshes when state changes, and the remove rocket action also calls a get rockets post

**Comment by AlexisReyes90** [comment]
Yeah I know, but sometimes when actions act up, it says it refreshes but will still hold on to previous data ( for some reason).

**Comment by KryoKorpz** [comment]
Gotcha; yeah I think that's just us not using the proper state (redux vs component state)

**Comment by KryoKorpz** [comment]
#134 
Checked the redirect; looks solid. It might have been since there was no error display. I added error display functionality on this PR.

**Comment by LisaCee** [comment]
Where do I get to the remove rocket functionality?  I can see my created rocket and I can get to the edit screen, but then...

**Comment by KryoKorpz** [comment]
Hmmm I thought I removed the edit button; since we actually don't have an edit feature built, and I didn't want to tackle that. 

Looks like I didn't implement the delete rocket on the "rocket" page, I only put it on the create class page. I can go through and adjust that.

**Comment by KryoKorpz** [comment]
Delete rocket button on rocket page now

**Pull request merged**
